### ISSUE TITLE
Implement pruneDocuments() Apprwite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/demos-for-functions#75]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `pruneDocuments` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should scan all documents in all collections to read their `createdAt` attribute. If a document has this attribute and it's older than 5 years, remove the document.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Create `feat-implement-prune-documents-X` branch where `X` is programming language you used
- [ ] Create folder named `prune-documents` in the language folder of your choice
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒  = In progress - Someone is already working on this language
❌ =  Unassigned yet - This language can be assigned to you

| Function / Language  | Deno    | NodeJS   | PHP     | Python  | Ruby   | Dart | .NET    | Java | Kotlin |
| -------------        | --------| ---------| --------|-------- |------- |------|---------|------|--------|
|pruneDocuments           | ❌       | ❌        | ❌       | ❌      | ❌      |  ❌  | ❌      |❌    |❌      |

**Happy Appwriting!**

**Comment by avats-dev** [comment]
I want to implement this function for **`python`** language. Also, can you please guide me where can I find the whole structure of storage object and what do you mean by all collections. Please provide me the appropriate reference, happy to contribute to appwrite. Thanks !

**Comment by Meldiron** [comment]
@avats-dev Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by chandrikadeb7** [comment]
@Meldiron I want to take this up with Java and Python

**Comment by lohanidamodar** [comment]
@chandrikadeb7 assigned Java to you. All the best 🚀

**Comment by chandrikadeb7** [comment]
@Meldiron Can you help me with the Java implementation of this function? Which sdk to import and what to do?

**Comment by lohanidamodar** [comment]
@chandrikadeb7 You can use our [Kotlin SDK](https://github.com/appwrite/sdk-for-kotlin)

**Comment by foxy-eyed** [comment]
@Meldiron I would like to work on Ruby implementation.

**Comment by crossphoton** [comment]
Hi can I take the NodeJS implementation.
