### ISSUE TITLE
Implement addUpdatedAt() Apprwite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/demos-for-functions#77]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `addUpdatedAt` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should trigger on `database.documents.update` event and fill `updatedAt` attribute with the current time, if this rule for `updatedAt` is configured on a specific collection.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Create `feat-implement-add-updated-at-X` branch where `X` is programming language you used
- [ ] Create folder named `add-updated-at` in the language folder of your choice
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒  = In progress - Someone is already working on this language
❌ =  Unassigned yet - This language can be assigned to you

| Function / Language  | Deno    | NodeJS   | PHP     | Python  | Ruby   | Dart | .NET    | Java | Kotlin |
| -------------        | --------| ---------| --------|-------- |------- |------|---------|------|--------|
|addUpdatedAt           | ❌       | ❌        | ❌       | ❌      | ❌      |  ❌  | ❌      |❌    |❌      |

**Happy Appwriting!**

**Comment by sasagarw** [comment]
Hey @Meldiron I would be interested to work on this issue. I will do for `python` language.

**Comment by Illusion47586** [comment]
Hi @Meldiron I am interested in working for nodejs in this issue.

**Comment by sasagarw** [comment]
> Hey @Meldiron I would be interested to work on this issue. I will do for `python` language.

Should we just start with implementation @Meldiron or wait for you to assign us the task?

**Comment by Meldiron** [comment]
@sasagarw @Illusion47586  Hacktoberfest didn't start yet, so we will not assign issues yet. Please ask again on 1.10. and I will be more than happy to assign it to you 😇 I removed your comments to keep the issue clean.

**Comment by sasagarw** [comment]
Hey @Meldiron I would be interested to work on this issue. I will do it for `python` language.

**Comment by Meldiron** [comment]
@sarakaandorp Assigned it to you! All the best 🚀

**Comment by Illusion47586** [comment]
@Meldiron I am interested in doing this for nodejs. Please assign it to me.

**Comment by Meldiron** [comment]
@Illusion47586 Assigned it to you! All the best 🚀
