### ISSUE TITLE
Implement generateBitlyUrl() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/demos-for-functions#82]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `generateBitlyUrl` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take an `url` as an input, generate a short URL using [Bitly](https://bitly.com/) and output the shorten URL.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Create `feat-implement-generate-bitly-url-X` branch where `X` is programming language you used
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| generateBitlyUrl    | ❌   | ❌     | ❌  | ❌     | ❌   | ❌   | ❌   | ❌   | ❌     |

**Happy Appwriting!**

**Comment by arshxyz** [comment]
I would like to claim this issue, thanks.

**Comment by foxy-eyed** [comment]
Hi! I would like to implement it with Ruby.

**Comment by Meldiron** [comment]
@arshxyz @foxy-eyed   Hacktoberfest didn't start yet, so we will not assign issues yet. Please ask again on 1.10. and I will be more than happy to assign it to you 😇 I removed your comments to keep the issue clean.

**Comment by ssm0801** [comment]
Is hacktoberfest started ?

**Comment by avats-dev** [comment]
Hey, I'm working on implementing this for **`python`** language. Please assign me for the same. Thanks!

**Comment by sasagarw** [comment]
Hey @Meldiron I would be interested to work on this issue. I will do it for `java` language.

**Comment by Shylajhaa** [comment]
@Meldiron I can implement this in `PHP` and `Kotlin`

**Comment by arshxyz** [comment]
Hi, I'd like to claim this issue for `nodejs`, thanks.

**Comment by ssm0801** [comment]
I would like to worn on this ?
I will code in `python`

**Comment by DonnC** [comment]
I would like to try this in `python` and `dart`

**Comment by foxy-eyed** [comment]
Hi! Would like to implement this with `Ruby`

**Comment by Meldiron** [comment]
@avats-dev @sasagarw @Shylajhaa @ssm0801 Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by Meldiron** [comment]
@DonnC @foxy-eyed @arshxyz Assigned it to you! All the best 🚀

**Comment by eigengravy** [comment]
hi, i would love to implement this in deno

**Comment by christyjacob4** [comment]
@eigengravy assigned you. All the best :rocket:

**Comment by nCodesDotEU** [comment]
Hi, can I do it in Java?

**Comment by lohanidamodar** [comment]
@nCodesDotEU assigned Java to you. All the best 🚀
