### ISSUE TITLE
Implement generateGoogleMap() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/demos-for-functions#84]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `generateGoogleMap` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take `latitude` and `longitude` as an input, generate map preview using [Google Maps API](https://developers.google.com/maps) and save it into Appwrite Storage.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Create `feat-implement-generate-google-map-X` branch where `X` is programming language you used
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| generateGoogleMap   | ❌   | ❌     | ❌  | ❌     | ❌   | ❌   | ❌   | ❌   | ❌     |

**Happy Appwriting!**

**Comment by Meldiron** [comment]
@Aonepathan    Hacktoberfest didn't start yet, so we will not assign issues yet. Please ask again on 1.10. and I will be more than happy to assign it to you 😇 I removed your comment to keep the issue clean.

**Comment by Ares358** [comment]
Can I be assigned for this one? I'm implementing this using Python.

**Comment by Shylajhaa** [comment]
@Meldiron  I can implement this in `PHP` and `Kotlin`

**Comment by Meldiron** [comment]
@Shylajhaa @Ares358 Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by Aonepathan** [comment]
@Meldiron If possible, could I work on the Java portion of this item?

**Comment by Meldiron** [comment]
@Aonepathan Assigned it to you! All the best 🚀

**Comment by GunjanDhanuka** [comment]
Can I work on the Python and Dart portions of this issue? @Meldiron

**Comment by Meldiron** [comment]
@GunjanDhanuka Assigned it to you! All the best 🚀

**Comment by Kokoden** [comment]
Hey! :) Can I work on the NodeJS portion of this?

**Comment by lohanidamodar** [comment]
@Kokoden Assigned NodeJS to you. All the best 🚀
