### ISSUE TITLE
Implement generateInvoice2goInvoice() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/demos-for-functions#85]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `generateInvoice2goInvoice` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should trigger on `database.documents.create` event, get content of the document and use it to generate [Invoice2go](https://invoice.2go.com/) invoice. Finally, save the invoice to Appwrite Storage.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Create `feat-implement-generage-invoice2go-invoice-X` branch where `X` is programming language you used
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language       | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| generateInvoice2goInvoice | ❌   | ❌     | ❌  | ❌     | ❌   | ❌   | ❌   | ❌   | ❌     |

**Happy Appwriting!**

**Comment by niyoj** [comment]
Can you assign this task to me? I will be  very happy to contribute. I would like to work with PHP language,

**Comment by Meldiron** [comment]
@niyoj Assigned it to you! All the best 🚀

**Comment by niyoj** [comment]
@Meldiron Will be sending a PR soon.

**Comment by niyoj** [comment]
Can I get some hints regarding how to generate invoice2go invoice? I looked over the documentation in invoice2go but there is nothing I found that can be used to generate the invoice by giving the data from documents. May be I got wrong. So can you give me a little hint or reference that can be used.

**Comment by Meldiron** [comment]
@niyoj Hmm I just checked with them and it looks like they don't support API communication yet. I am sorry for the complications, but we will need to wait for their implementation before continuing this issue.

**Comment by niyoj** [comment]
@Meldiron So, I think I will be working on another issue till then.
