### ISSUE TITLE
Implement generateInvoicelyInvoice() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/demos-for-functions#86]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `generateInvoicelyInvoice` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should trigger on `database.documents.create` event, get content of the document and use it to generate [Invoicely](https://invoicely.com/) invoice. Finally, save the invoice to Appwrite Storage.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Create `feat-implement-generate-invoicely-invoice-X` branch where `X` is programming language you used
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language      | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------------ | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| generateInvoicelyInvoice | ❌   | ❌     | ❌  | ❌     | ❌   | ❌   | ❌   | ❌   | ❌     |

**Happy Appwriting!**

**Comment by ashwinexe** [comment]
Hey I am interested to implement this function.
Note: Before assigning I want to let you know I am **new** to appwrite functions. Will be needing help from discord :)

**Comment by Meldiron** [comment]
@ashwinexe Sure, both Appwrite core team and Appwrite community are ready to help you 😊

Please let me know which language you would like to be assigned to.

**Comment by ashwinexe** [comment]
> @ashwinexe Sure, both Appwrite core team and Appwrite community are ready to help you 😊
> 
> Please let me know which language you would like to be assigned to.

Awesome, Please assign me to NodeJS

**Comment by lohanidamodar** [comment]
@ashwinexe Assigned NodeJS to you. All the best 🚀
