### ISSUE TITLE
Implement generateUnsplashImage() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/demos-for-functions#87]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `generateUnsplashImage` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take a `keyword` as an input, use it as a keyword for Unsplash search, pick the first image and return `imageUrl` and `imageAuthor`.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Create `feat-implement-generate-unsplash-image-X` branch where `X` is programming language you used
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language   | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| --------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| generateUnsplashImage | ❌   | ❌     | ❌  | ❌     | ❌   | ❌   | ❌   | ❌   | ❌     |

**Happy Appwriting!**

**Comment by avats-dev** [comment]
Hey, I'm working on implementing this in **`python`**. Please assign me for the same. Thanks.

**Comment by Ares358** [comment]
I'm also working on this one using Python. Can two people be assigned for the same task?

**Comment by DonnC** [comment]
Hie, can i take this with `dart`

**Comment by Meldiron** [comment]
@DonnC @avats-dev Assigned it to you! All the best 🚀

**Comment by Meldiron** [comment]
@Ares358 Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by bistaastha** [comment]
I can work on this over NodeJS.

**Comment by Meldiron** [comment]
@bistaastha Assigned it to you! All the best 🚀

**Comment by avats-dev** [comment]
Added PR for implementing this in python.

**Comment by Meldiron** [comment]
@avats-dev Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by peterchu999** [comment]
Hey, I wanna try to working on implementing this in `Java`. please assign to me Thanks

**Comment by crossphoton** [comment]
Hey can I take the `deno` implementation.
