### ISSUE TITLE
Implement generateXeroInvoice() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/demos-for-functions#88]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `generateXeroInvoice` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should trigger on `database.documents.create` event, get content of the document and use it to generate [Xero](https://www.xero.com/) invoice. Finally, save the invoice to Appwrite Storage.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Create `feat-implement-generate-xero-invoice-X` branch where `X` is programming language you used
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| generateXeroInvoice | ❌   | ❌     | ❌  | ❌     | ❌   | ❌   | ❌   | ❌   | ❌     |

**Happy Appwriting!**

**Comment by Jaideep07** [comment]
Hello 😃, I would like to work on this in python language could you pls assign me this issue.

**Comment by christyjacob4** [comment]
@Jaideep07  Assigned to you! All the best :rocket:

**Comment by Daybringer** [comment]
Hi, I would like to do the NodeJS and Deno implementation.

**Comment by lohanidamodar** [comment]
@Daybringer assigned Deno to you. If no one else is assigned to nodejs by the time you finish with deno, we might assign you that as well. All the best 🚀 .

**Comment by crossphoton** [comment]
@lohanidamodar @christyjacob4 Can I work on the NodeJS implementation?
