### ISSUE TITLE
Implement getInternetSpeed() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/demos-for-functions#89]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `getInternetSpeed` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should use any Speedtest provider to check the download and upload speed of the server. The results should be provided as an output of the function.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Create `feat-implement-get-internet-speed-X` branch where `X` is programming language you used
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| getInternetSpeed            | ❌   | ❌     | ❌  | ❌     | ❌   | ❌   | ❌   | ❌   | ❌     |

**Happy Appwriting!**

**Comment by Ares358** [comment]
Can I be assigned for this one? I'm implementing this using Python.

**Comment by ssm0801** [comment]
Can I get this one ?
I will code in `python`

**Comment by Meldiron** [comment]
@ssm0801 Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by Meldiron** [comment]
@Ares358 Assigned it to you! All the best 🚀

**Comment by mukeshmjn** [comment]
@Meldiron assign for nodejs to me

**Comment by Meldiron** [comment]
@mukeshmjn Assigned it to you! All the best 🚀

**Comment by eigengravy** [comment]
hi, i would love to have a go at deno

**Comment by GunjanDhanuka** [comment]
@Meldiron can you assign this to me in ```dart```?

**Comment by christyjacob4** [comment]
@eigengravy Assigned you! All the best :rocket:

**Comment by christyjacob4** [comment]
@GunjanDhanuka Assinged to you! All the best

**Comment by GunjanDhanuka** [comment]
> @Meldiron can you assign this to me in `dart`?

Actually there is a problem since I cannot find any package/API that works for Dart applications. Python has a convenient SpeedTest CLI package but that doesn't seem to work for Dart. Also I found a package but that depends on Flutter and thus the execution steps will change. Will it be fine to use a Flutter package in this case then? @christyjacob4  @Meldiron

**Comment by GunjanDhanuka** [comment]
> @GunjanDhanuka Assinged to you! All the best

I have made a PR for the same! Please review it.

**Comment by Meldiron** [comment]
@GunjanDhanuka Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by jash-desai** [comment]
Can I work for this in Dart? @Meldiron

**Comment by lohanidamodar** [comment]
@jash-desai as you can see the Dart is already assigned. Please try other language or other demo issues. Thank you.

**Comment by nCodesDotEU** [comment]
Can I work for this in Java?

**Comment by lohanidamodar** [comment]
@nCodesDotEU assigned to you. All the best 🚀

**Comment by akashgp09** [comment]
@Meldiron @christyjacob4 I am working on the ruby one.

**Comment by lohanidamodar** [comment]
@akashgp09 assigned ruby to you. All the best 🚀
