### ISSUE TITLE
Implement getStripePaymentStatus() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/demos-for-functions#90]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `getStripePaymentStatus` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take `stripePaymentId` as an input, check the status of the payment and respond with the payment status.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Create `feat-implement-get-stripe-payment-status-X` branch where `X` is programming language you used
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language    | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ---------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| getStripePaymentStatus | ❌   | ❌     | ❌  | ❌     | ❌   | ❌   | ❌   | ❌   | ❌     |

**Happy Appwriting!**

**Comment by mukeshmjn** [comment]
@Meldiron assign For Nodejs to me . I would work on this

**Comment by Meldiron** [comment]
@mukeshmjn Assigned it to you! All the best 🚀

**Comment by abxhr** [comment]
@Meldiron I would love to work on the Python Implementation 🙋‍♂️

**Comment by lohanidamodar** [comment]
@abxhr assigned python to you. All the best 🚀

**Comment by eigengravy** [comment]
hi, can i work on the deno implementation?

**Comment by lohanidamodar** [comment]
@eigengravy assigned deno to you. All the best 🚀
