### ISSUE TITLE
Implement sendRequest() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/demos-for-functions#91]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `sendRequest` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should replace our current [Appwrite Tasks](https://appwrite.io/docs/tasks) feature. It should take the configuration of the HTTP request as input and send the HTTP request.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Create `feat-implement-send-request-X` branch where `X` is programming language you used
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| sendRequest            | ❌   | ❌     | ❌  | ❌     | ❌   | ❌   | ❌   | ❌   | ❌     |

**Happy Appwriting!**

**Comment by ssm0801** [comment]
Can I get this one ?
I will code in `python`

**Comment by Meldiron** [comment]
@ssm0801 Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by Sin-Sumit** [comment]
@Meldiron Can I work on this using NodeJs?

**Comment by shujathkhan** [comment]
@Meldiron I can contribute to NodeJS, Python, Java, Kotlin or .Net. You can assign me any one of them, later I can contribute to the other languages as well.

**Comment by Meldiron** [comment]
@Sin-Sumit Assigned it to you! All the best 🚀

@shujathkhan Assigned you `.Net` since that is a rare skill 😎 and `python` so you are not bored 😛  Once finished, I can assign more languages or you could do another function.

**Comment by lohanidamodar** [comment]
@DjDeveloperr Assigned deno to you. All the best 🚀

**Comment by crossphoton** [comment]
@Meldiron NodeJS assigned but not mentioned.

**Comment by Sin-Sumit** [comment]
hey, @crossphoton I'm working on NodeJs.

**Comment by Meldiron** [comment]
@crossphoton My bad 😞 I commented but forgot to update the table... Updated it now. Check out other functions we need to implement, many of them have NodeJS unassigned.
