### ISSUE TITLE
Implement sendSMS() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/demos-for-functions#92]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `sendSMS` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take `phoneNumber` and `text` as input and send an SMS using [Twilio](https://www.twilio.com/) to this number.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Create `feat-implement-send-sms-X` branch where `X` is programming language you used
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| sendSMS             | ❌   | ❌     | ❌  | ❌     | ❌   | ❌   | ❌   | ❌   | ❌     |

**Happy Appwriting!**

**Comment by ssm0801** [comment]
Can I take this ? I'll work in `python`

**Comment by Rishavgupta12345** [comment]
i have a question . if i make the function to send SMS , then how should i make a working function because the layout and the buttons which will be required won't be provided and the app will not work .

it will be like a demo function , so do you guys want a perfect working function ?

**Comment by Shylajhaa** [comment]
@Meldiron  I can implement this in `PHP` and `Kotlin`

**Comment by ssm0801** [comment]
Can I get this one ?
I will code in `python`

**Comment by DonnC** [comment]
Howdy, i think i will go for `dart` on this one

**Comment by Rishavgupta12345** [comment]
i am working on this using kotlin

**Comment by Meldiron** [comment]
@Shylajhaa Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by Meldiron** [comment]
@ssm0801 @Rishavgupta12345  @DonnC  Assigned it to you! All the best 🚀

**Comment by TheLearneer** [comment]
Hi there, I would like to work on it using Node.js.

**Comment by Meldiron** [comment]
@TheLearneer Assigned it to you! All the best 🚀

**Comment by DjDeveloperr** [comment]
Hey, I'd like to do it using Deno.

**Comment by christyjacob4** [comment]
@DjDeveloperr  Assigned it to you! All the best :rocket:

**Comment by Rishavgupta12345** [comment]
bro i have made the pull request #100  please review it

**Comment by akashgp09** [comment]
@Meldiron @christyjacob4 I am working on the ruby one.

**Comment by Meldiron** [comment]
@Rishavgupta12345 Thanks for the PR! 🤯 Please give us some time to review it.

@akashgp09 Assigned it to you! All the best 🚀

**Comment by kkhitesh** [comment]
Hey, I would like to work on Java Implementation, could you assign it to me

**Comment by lohanidamodar** [comment]
@kkhitesh Assigned Java to you. All the best 🚀

**Comment by niyoj** [comment]
Can I work in this issue in PHP language? This issue and issue to implement WhatsApp message functions seems to be quite similar. So, I would like to work in this issue too.

**Comment by Meldiron** [comment]
@niyoj Assigned it to you! All the best 🚀
