### ISSUE TITLE
Implement sendWhatsAppMessage() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/demos-for-functions#93]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `sendWhatsAppMessage` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take `phoneNumber` and `text` as input and send a WhatsApp message using [Twilio](https://www.twilio.com/) to this number.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Create `feat-implement-send-whats-app-msg-X` branch where `X` is programming language you used
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| sendWhatsAppMessage | ❌   | ❌     | ❌  | ❌     | ❌   | ❌   | ❌   | ❌   | ❌     |

**Happy Appwriting!**

**Comment by ssm0801** [comment]
Can I take this ? I'll work in `python`

**Comment by Shylajhaa** [comment]
@Meldiron Can I choose to implement this in multiple languages?

**Comment by Phoenix-031** [comment]
@Meldiron I would like to implement this is python.

**Comment by Shylajhaa** [comment]
@Meldiron  I can implement this in `PHP` and `Kotlin`

**Comment by DonnC** [comment]
I would like to go for `python`

**Comment by ssm0801** [comment]
I would like to work on this ?
I will code in `Java`

**Comment by Meldiron** [comment]
@DonnC @ssm0801 Assigned it to you! All the best 🚀

**Comment by Meldiron** [comment]
@Shylajhaa Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by DonnC** [comment]
> @DonnC @ssm0801 Assigned it to you! All the best 🚀

thank you but i requested for `python` can you confirm

**Comment by Meldiron** [comment]
@DonnC Whoops, my bad, thanks for the correction. Sure, `python` is yours 🥳

**Comment by mukeshmjn** [comment]
@Meldiron assign for nodejs to me

**Comment by Meldiron** [comment]
@mukeshmjn Assigned it to you! All the best 🚀

**Comment by divyanshkul** [comment]
@Meldiron I would like to work in ```dart```

**Comment by niyoj** [comment]
Can I work in this issue in PHP language?

**Comment by Meldiron** [comment]
@niyoj Assigned it to you! All the best 🚀

**Comment by alfiankan** [comment]
i can implement in kotlin
please assign to me

**Comment by lohanidamodar** [comment]
@alfiankan assigned kotlin to you. All the best 🚀
