### ISSUE TITLE
Implement subscribeToMailchimp() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/demos-for-functions#94]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `subscribeToMailchimp` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take an `email` as input and register this email as a subscriber to [Mailchimp](https://mailchimp.com/) newsletter.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Create `feat-implement-subscribe-to-mailchimp-X` branch where `X` is programming language you used
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language  | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| -------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| subscribeToMailchimp | ❌   | ❌     | ❌  | ❌     | ❌   | ❌   | ❌   | ❌   | ❌     |

**Happy Appwriting!**

**Comment by anmol-Git** [comment]
I will like to work on this issue , Can you Please assign this issue to me.

**Comment by Nikhil-1503** [comment]
I would like to work on this issue in Java.

**Comment by Meldiron** [comment]
@Nikhil-1503 Assigned it to you! All the best 🚀

**Comment by Meldiron** [comment]
@anmol-Git Sure, we can 😊 Can you please specify the coding language?

**Comment by anmol-Git** [comment]
@Meldiron  will do this in java and kotlin

**Comment by Meldiron** [comment]
@anmol-Git Great, thanks for the clarification. Go ahead, good luck 💪 I assigned you to Kotlin, Java is already taken.

**Comment by benceHornyak** [comment]
Hey. Can i work on the nodejs part of this? :)

**Comment by christyjacob4** [comment]
@benceHornyak  All the best. Assinged you :smile:

**Comment by Meldiron** [comment]
@Rishabh-Negi Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by YarinAyash1** [comment]
I would like to work on this issue in PHP.

**Comment by lohanidamodar** [comment]
@YarinAyash1 Assigned PHP to you. All the best 🚀
