### ISSUE TITLE
Implement subscribeToSendGrid() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/demos-for-functions#95]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `subscribeToSendGrid` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take an `email` as input and register this email as a subscriber to [SendGrid](https://sendgrid.com/) newsletter.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Create `feat-implement-subscribe-to-send-grid-X` branch where `X` is programming language you used
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| subscribeToSendGrid | ❌   | ❌     | ❌  | ❌     | ❌   | ❌   | ❌   | ❌   | ❌     |

**Happy Appwriting!**

**Comment by Shylajhaa** [comment]
@Meldiron  I can implement this in `PHP` and `Kotlin`

**Comment by Meldiron** [comment]
@Shylajhaa Assigned it to you! All the best 🚀

**Comment by ishaanmehta4** [comment]
Hey @Meldiron, if I have understood it correctly, the function just needs to add the email as a contact to some sendgrid list right?
https://docs.sendgrid.com/api-reference/contacts/add-or-update-a-contact

Also, I hope I can use an external library such as axios to make the request to SendGrid's API endpoint.

**Comment by GunjanDhanuka** [comment]
I would like to implement this in Python! @Meldiron

**Comment by Meldiron** [comment]
@ishaanmehta4 We didn't dig too deep into implementation, but filling contact group seems correct 👍

@GunjanDhanuka Assigned it to you! All the best 🚀

**Comment by ishaanmehta4** [comment]
Thanks @Meldiron , can you please assign nodejs to me? I wish to work on that.

**Comment by christyjacob4** [comment]
@ishaanmehta4 Assigned you
