### ISSUE TITLE
Implement textToSpeech() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/demos-for-functions#96]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `textToSpeech` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take `text` as an input, generate an MP3 file using [Google Text-to-speech API](https://cloud.google.com/text-to-speech) and save it into Appwrite Storage.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Create `feat-implement-text-to-speech-X` branch where `X` is programming language you used
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| textToSpeech        | ❌   | ❌     | ❌  | ❌     | ❌   | ❌   | ❌   | ❌   | ❌     |

**Happy Appwriting!**

**Comment by Ares358** [comment]
I'd like to work on this one!

**Comment by Rishavgupta12345** [comment]
can i work on this issue ? i want to participate in hactoberfest .

i will write the code in kotlin

**Comment by avats-dev** [comment]
Hey, I am working on implementing this in `python`. Please assign me for the same. Thanks.

**Comment by ssm0801** [comment]
I would like to work on this ?
I will code in `python`

**Comment by Meldiron** [comment]
@Rishavgupta12345 @avats-dev @ssm0801 Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by Sin-Sumit** [comment]
@Meldiron Can I work on this using NodeJs?

**Comment by Jaideep07** [comment]
Hello @Meldiron 👋🏻, I could work on this in python

**Comment by rajatkeshri** [comment]
Hi, can you assign this to me for python? I have already created a PR for this.

**Comment by christyjacob4** [comment]
@Jaideep07  All the best :rocket:

**Comment by christyjacob4** [comment]
@rajatkeshri We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by Rishabh-Negi** [comment]
Hey i Would like to work on this in  Dart

**Comment by R055A** [comment]
Hi. I am interested in being assigned for PHP and/or Ruby, thanks.

**Comment by Meldiron** [comment]
@Rishabh-Negi @R055A  Assigned it to you! All the best 🚀

**Comment by JeevaSaravanan** [comment]
Hi ! I would like to work on this in Java.

**Comment by lohanidamodar** [comment]
@JeevaSaravanan Assigned java to you. All the best 🚀
