### ISSUE TITLE
Implement translateText() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/demos-for-functions#97]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `translateText` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take `text`, `sourceLanguage` and `destinationLanguage` as an input, use [Google Translate API](https://cloud.google.com/translate) to translate it and output the translated version.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Create `feat-implement-translate-text-X` branch where `X` is programming language you used
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| translateText       | ❌   | ❌     | ❌  | ❌     | ❌   | ❌   | ❌   | ❌   | ❌     |

**Happy Appwriting!**

**Comment by sanyud24** [comment]
May I work on this issue using Kotlin language ?

**Comment by Meldiron** [comment]
@sanyud24  Hacktoberfest didn't start yet, so we will not assign issues yet. Please ask again on 1.10. and I will be more than happy to assign it to you 😇 I removed your comment to keep the issue clean.

**Comment by Rishavgupta12345** [comment]
can i work on this issue ? i want to participate in hactoberfest .

i will write the code in kotlin

**Comment by avats-dev** [comment]
Hey, I'm working on implementing this in `python`. Please assign me for the same. Thanks.

**Comment by ssm0801** [comment]
Can I get this one ?
I will code in `python`

**Comment by Meldiron** [comment]
@Rishavgupta12345 @avats-dev Assigned it to you! All the best 🚀

**Comment by Meldiron** [comment]
@ssm0801 We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by Obnoxious-coder** [comment]
Can you assign this to me for python

**Comment by Obnoxious-coder** [comment]
i would like to work on this one in Nodejs

**Comment by Meldiron** [comment]
@Obnoxious-coder Assigned it to you! All the best 🚀

**Comment by sanyud24** [comment]
I would like  to implement in java.

**Comment by christyjacob4** [comment]
@sanyud24 All the best :rocke

**Comment by Rishabh-Negi** [comment]
Hey I would like to work on this in Dart
but is seems to assigned to @avats-dev  who applied for python

**Comment by avats-dev** [comment]
Opened PR for its implementation in python, do review it and LMK of any suggestions. 👍

**Comment by Meldiron** [comment]
@Rishabh-Negi Assigned it to you! All the best 🚀

Whoops I put avast-dev into wrong column, thanks for letting me know 🙏

**Comment by akashgp09** [comment]
@Meldiron @christyjacob4 I am working on the ruby one.

**Comment by lohanidamodar** [comment]
@akashgp09 Assigned to you. All the best 🚀

**Comment by noobkid2411** [comment]
Hi,I would like to implement this function in php!

**Comment by lohanidamodar** [comment]
@noobkid2411 assigned PHP to you. All the best 🚀
