### ISSUE TITLE
Implement tweetNewMembership() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/demos-for-functions#98]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `tweetNewMembership` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should trigger on `team.membership.create` event, and post a tweet that a new user joined a team.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Create `feat-implement-tweet-new-membership-X` branch where `X` is programming language you used
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| tweetNewMembership            | ❌   | ❌     | ❌  | ❌     | ❌   | ❌   | ❌   | ❌   | ❌     |

**Happy Appwriting!**

**Comment by Ares358** [comment]
Can I be assigned for this one? I'm implementing this using Python.

**Comment by arshxyz** [comment]
Hi, I'd like to claim this for `nodejs`.

**Comment by Meldiron** [comment]
@Ares358 @arshxyz Assigned it to you! All the best 🚀

**Comment by rosiegamgee718** [comment]
Can I try this in Java, please?

**Comment by Meldiron** [comment]
@rosiegamgee718 Assigned it to you! All the best 🚀

**Comment by Meldiron** [comment]
@arshxyz I noticed you created draft PR. That means you don't want us to review it yet. Please un-draft it once it's ready 😇

**Comment by niyoj** [comment]
I would like to work on this issue in PHP language.

**Comment by Meldiron** [comment]
@niyoj Just assigned you to 2 issues related to Twilio. Please finish these, then we can assign you more 😊

**Comment by codingsamurai-10** [comment]
I would like to take this up for PHP @Meldiron

**Comment by divyanshkul** [comment]
Hey @Meldiron I would like to work on this in ```dart```

**Comment by eigengravy** [comment]
hi, can I work on this for deno?

**Comment by lohanidamodar** [comment]
@eigengravy @divyanshkul Assigned deno and dart respectively. All the best 🚀

**Comment by lohanidamodar** [comment]
@codingsamurai-10 Assigned PHP to you, all the best 🚀
